output_dirs:
  output_interpolate: "./output/interpolate"
  output_slowmotion: "./output/slowmotion"
model: "./pretrained_models/pretrained_VFIformer/net_220.pth"
gpu_ids: "0"
auto_launch_browser: True
server_port: 7860
server_name: "0.0.0.0"
